### ISSUE TITLE
generateproto not generating int fields

### ISSUE THREAD

**Issue by scout-d** [socotecio/django-socio-grpc#127] opened 2023-01-23 22:46 UTC
Hello and hope you're doing well!

I started using this and ran into a small issue. I created a model where I'm using an integer field for state with a list of choices.
![Screenshot 2023-01-23 at 5 45 19 PM](https://user-images.githubusercontent.com/118021447/214166744-7bcc0407-4225-4854-b530-5bec6ab1e90c.png)

However, any time I run `python manage.py generateproto` it creates the state field as a string in the proto file. 
![Screenshot 2023-01-23 at 5 48 15 PM](https://user-images.githubusercontent.com/118021447/214168523-6eb924fd-a8c1-40b3-b759-56f09f200706.png)

Is this intended behavior or a known issue? I've been working around it by generating proto files with `python -m grpc_tools.protoc` and manually updating the import statements, but it would be nice if the `generateproto` command could do this. If I'm missing anything, let me know and thanks in advance for the help!

**Comment by legau** [comment] 2023-01-24 10:42
Hi @scout-d 
This is indeed not intended behavior, we're in the process of rewriting the proto generation code (#125) so this will be fixed in the new release

Thank you for your issue !

**Closed** 2023-01-31 13:52 UTC
